from pathlib import Path
p=Path('sediment-resuspension.html')
s=p.read_text(encoding='utf-8')
if 'r83-sediment-spatial-flow' in s: raise SystemExit('already patched')
s=s.replace('<title>粒子堆積・再懸濁ラボ</title>','<title>粒子堆積・再懸濁ラボ</title><meta name="r83-sediment-spatial-flow" content="tap-lift-drag-flow-transport-redeposit">',1)
extra=r'''<style id="r83-sediment-flow-style">.r83-flow-overlay{position:absolute;z-index:8;touch-action:none;cursor:crosshair;background:transparent}.r83-flow-badge{display:inline-flex;align-items:center;gap:6px;padding:5px 8px;border:1px solid #5fd3ff77;border-radius:999px;background:#092033;color:#bdeeff;font-size:11px;font-weight:850}</style>
<script id="r83-sediment-spatial-flow">
(()=>{
if(typeof APP==="undefined"||APP.type!=="sediment")return;
const canvas=document.getElementById("mainCv"),stage=canvas&&canvas.closest(".stage");if(!canvas||!stage)return;stage.style.position="relative";
const stageHelp=stage.querySelector(".stageHelp strong");if(stageHelp)stageHelp.textContent="👆 タップ：その場所の底泥を舞い上げる ／ ドラッグ：その向きに水流を描く";
const oldPanel=document.querySelector(".sediment-touch-panel");if(oldPanel){oldPanel.querySelector("b").textContent="🌊 直接実験：";const span=oldPanel.querySelector("span:not(.status)");if(span)span.textContent="タップは局所再懸濁、ドラッグは数秒残る局所流れ。粒子が運ばれ、流れが弱まると再び沈みます。"}
const badge=document.createElement("span");badge.className="r83-flow-badge";badge.textContent="水流 0本";stage.querySelector(".stageHelp")?.appendChild(badge);
const overlay=document.createElement("div");overlay.className="r83-flow-overlay";overlay.setAttribute("aria-label","タップで底泥を舞い上げ、ドラッグで局所水流を描く操作面");stage.appendChild(overlay);
function syncOverlay(){overlay.style.left=canvas.offsetLeft+"px";overlay.style.top=canvas.offsetTop+"px";overlay.style.width=canvas.offsetWidth+"px";overlay.style.height=canvas.offsetHeight+"px"}syncOverlay();addEventListener("resize",syncOverlay);
let flows=[],gesture=null,liftBursts=[];const status=oldPanel&&oldPanel.querySelector(".status");
const point=e=>{const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*canvas.width,y:(e.clientY-r.top)/r.height*canvas.height}};const norm=q=>({x:clamp((q.x-45)/810,0,1),y:clamp((445-q.y)/390,.02,.93)});
function liftAt(q){const n=norm(q),calc=sedimentCalc(),near=state.parts.filter(p=>p.phase==="bed").sort((a,b)=>Math.abs(a.x-n.x)-Math.abs(b.x-n.x));let lifted=0;for(const p of near.slice(0,18)){if(Math.abs(p.x-n.x)>.18&&lifted>=6)break;p.phase="suspended";p.x=clamp(n.x+(rnd()-.5)*.13,0,1);p.y=.035+rnd()*.055;p.v=.24+Math.max(0,.34-calc.extra.settle*.07)+rnd()*.25;lifted++}liftBursts.push({x:q.x,y:445,t:1});liftBursts=liftBursts.slice(-8);if(status)status.textContent=`タップで ${lifted}粒を再懸濁。次は横へドラッグして運んでみよう。`;running=true;document.getElementById("playPause").textContent="⏸ 一時停止";advance(.035)}
function addFlow(from,to){const dx=to.x-from.x,dy=to.y-from.y,len=Math.hypot(dx,dy);if(len<5)return;const n=norm(to),strength=clamp(len/42,.28,1.25);flows.push({x:n.x,y:n.y,dirX:dx/len,dirY:-dy/len,strength,life:1,px:to.x,py:to.y});if(flows.length>42)flows.splice(0,flows.length-42);badge.textContent=`水流 ${flows.length}本`}
const baseDomainStep=domainStep;domainStep=function(dt){baseDomainStep(dt);if(APP.type!=="sediment"||!flows.length)return;const threshold=sedimentCalc().extra.threshold;for(const f of flows)f.life=Math.max(0,f.life-dt*.16);flows=flows.filter(f=>f.life>.02);for(const p of state.parts){let ax=0,ay=0,local=0,bottomLift=0;for(const f of flows){const dx=p.x-f.x,dy=p.y-f.y,d=Math.hypot(dx,dy),rad=.19;if(d>=rad)continue;const w=(1-d/rad)*f.life*f.strength;ax+=f.dirX*w;ay+=f.dirY*w;local+=w;if(f.y<.18)bottomLift=Math.max(bottomLift,w)}if(p.phase==="bed"){if(bottomLift>threshold*.55&&rnd()<dt*(bottomLift-threshold*.35)*2.8){p.phase=bottomLift>.55?"suspended":"bedload";p.y=.035+rnd()*.04;p.v=.08+bottomLift*.22}}else if(local>0){const mobility=p.phase==="bedload"?.45:1;p.x=clamp(p.x+dt*ax*.115*mobility,0,1);p.y=clamp(p.y+dt*ay*.065*mobility,.02,.93);if(p.phase==="suspended")p.v+=ay*dt*.07}}badge.textContent=`水流 ${flows.length}本`};
const baseDrawAll=drawAll;drawAll=function(){baseDrawAll();if(APP.type!=="sediment")return;const ctx=canvas.getContext("2d");ctx.save();ctx.lineCap="round";for(const f of flows){const x=45+f.x*810,y=445-f.y*390,L=42*f.strength*f.life,dx=f.dirX*L,dy=-f.dirY*L;ctx.globalAlpha=.18+.72*f.life;ctx.strokeStyle="#78e7ff";ctx.fillStyle="#78e7ff";ctx.lineWidth=3+2*f.strength;ctx.beginPath();ctx.moveTo(x-dx*.35,y-dy*.35);ctx.lineTo(x+dx*.65,y+dy*.65);ctx.stroke();const a=Math.atan2(dy,dx),tx=x+dx*.65,ty=y+dy*.65;ctx.beginPath();ctx.moveTo(tx,ty);ctx.lineTo(tx-10*Math.cos(a-.5),ty-10*Math.sin(a-.5));ctx.lineTo(tx-10*Math.cos(a+.5),ty-10*Math.sin(a+.5));ctx.closePath();ctx.fill()}for(const b of liftBursts){ctx.globalAlpha=b.t;ctx.strokeStyle="#b8f2ff";ctx.lineWidth=4;ctx.beginPath();ctx.arc(b.x,b.y,(1-b.t)*75+16,Math.PI,Math.PI*2);ctx.stroke();b.t-=.03}liftBursts=liftBursts.filter(b=>b.t>0);ctx.globalAlpha=1;if(flows.length){ctx.fillStyle="rgba(5,17,29,.82)";ctx.fillRect(585,54,260,34);ctx.fillStyle="#bcefff";ctx.font="bold 12px system-ui";ctx.fillText("🌊 描いた流れが粒子を運搬中",600,76)}ctx.restore()};
overlay.addEventListener("pointerdown",e=>{if(e.button!==undefined&&e.button!==0)return;const q=point(e);gesture={start:q,last:q,moved:false};overlay.setPointerCapture?.(e.pointerId);e.preventDefault()});overlay.addEventListener("pointermove",e=>{if(!gesture)return;const q=point(e),d=Math.hypot(q.x-gesture.last.x,q.y-gesture.last.y);if(d>=5){addFlow(gesture.last,q);gesture.last=q;gesture.moved=true;if(status)status.textContent="水流を描いています。青い矢印の向きへ浮遊粒子が運ばれます。";running=true;document.getElementById("playPause").textContent="⏸ 一時停止"}e.preventDefault()});
function endGesture(e){if(!gesture)return;if(!gesture.moved)liftAt(gesture.start);else{if(status)status.textContent="流れを描きました。流れが弱まったあと、粒径ごとの再堆積位置を比べよう。";drawAll()}gesture=null;e.preventDefault()}overlay.addEventListener("pointerup",endGesture);overlay.addEventListener("pointercancel",endGesture);
})();
</script>'''
assert '</body>' in s
s=s.replace('</body>',extra+'\n</body>',1)
p.write_text(s,encoding='utf-8')
print('sediment patched')
