from pathlib import Path
p=Path('ant-colony.html')
s=p.read_text(encoding='utf-8')
if 'r83-ant-individual-inspector' in s: raise SystemExit('already patched')
s=s.replace('<title>アリの巣・役割分担・資源管理ラボ</title>','<title>アリの巣・役割分担・資源管理ラボ</title><meta name="r83-ant-individual-inspector" content="tap-ant-tracking-resource-flow-bottleneck">',1)
extra=r'''<style id="r83-ant-inspector-style">.r83-ant-overlay{position:absolute;z-index:12;touch-action:none;cursor:crosshair;background:transparent;pointer-events:none}.r83-ant-inspector{display:grid;grid-template-columns:1.2fr .8fr;gap:8px;margin:9px 0 0;padding:10px 11px;border:1px solid #5fd3ff77;border-radius:13px;background:#0e2031}.r83-ant-inspector b{color:#ffd85a}.r83-ant-inspector .detail,.r83-ant-inspector .bottle{font-size:12px;line-height:1.65}.r83-ant-inspector .bottle{padding:7px 9px;border-radius:9px;background:#091725;color:#cce7f6}#r83InspectBtn.on{background:#ffd85a;color:#211a00;border-color:#d4b53b}@media(max-width:600px){.r83-ant-inspector{grid-template-columns:1fr}}</style>
<script id="r83-ant-individual-inspector">
(()=>{
const canvas=document.getElementById("mainCv"),stage=canvas&&canvas.closest(".stage"),toolbar=document.querySelector('[data-tour="controls"]');if(!canvas||!stage||!toolbar)return;stage.style.position="relative";
const inspectBtn=document.createElement("button");inspectBtn.id="r83InspectBtn";inspectBtn.type="button";inspectBtn.textContent="🔎 個体観察";const scenario=document.getElementById("scenarioBtn");toolbar.insertBefore(inspectBtn,scenario);
const overlay=document.createElement("div");overlay.className="r83-ant-overlay";overlay.setAttribute("aria-label","個体観察モード：アリをタップして追跡");stage.appendChild(overlay);function syncOverlay(){overlay.style.left=canvas.offsetLeft+"px";overlay.style.top=canvas.offsetTop+"px";overlay.style.width=canvas.offsetWidth+"px";overlay.style.height=canvas.offsetHeight+"px"}syncOverlay();addEventListener("resize",syncOverlay);
const panel=document.createElement("div");panel.className="r83-ant-inspector";panel.innerHTML='<div class="detail"><b>🔎 個体観察</b><div data-detail>「個体観察」を選び、気になるアリをタップ。</div></div><div class="bottle" data-bottle>コロニーの制約を判定中…</div>';stage.insertAdjacentElement("afterend",panel);const detail=panel.querySelector("[data-detail]"),bottle=panel.querySelector("[data-bottle]");
let inspect=false,selected=null,trail=[],lastTrail=null;const roleName={forage:"採餌",dig:"掘削",nurse:"育児",vent:"換気"},roleColor={forage:"#ffe36a",dig:"#ff9b74",nurse:"#9ee6b2",vent:"#8fcdf7"};
function oxygenNow(){const vent=ants.filter(a=>a.state==="vent").length;return Math.max(0,Math.min(1,.45+vent/Math.max(1,ants.length)*1.8+nest*.25-rain*.35))}
function bottleneck(){const p=par(),oxygen=oxygenNow(),roles={forage:0,dig:0,nurse:0,vent:0};for(const a of ants)roles[a.state]=(roles[a.state]||0)+1;if(store<14)return["🍚 食料","食料庫が少ない。採餌個体と餌場への経路が律速。"];if(oxygen<.3)return["💨 換気","地下の酸素余裕が小さい。豪雨時は換気個体が重要。"];if(health<.55)return["🐜 育児","幼虫健康が低下。食料と育児個体の両方を確認。"];if(nest<.48&&p.dig<.4)return["⛏️ 掘削","食料はあるが巣の拡張が遅い。掘削配分が律速。"];if(roles.forage<Math.max(2,ants.length*.18)&&store<45)return["🧭 採餌配分","採餌個体が少なく、将来の食料不足が起こりやすい。"];return["✓ 大きな制約なし","採餌・育児・掘削・換気が概ね釣り合っている。"]}
function taskText(a){if(a.state==="forage")return a.carry?"餌を持って入口へ帰還中":"餌場を探して移動中";if(a.state==="dig")return"地下で坑道・巣室を拡張中";if(a.state==="nurse")return"育児室へ移動して幼虫を世話";return"入口付近で換気中"}
function pherText(a){const near=pher.filter(q=>Math.hypot(q.x-a.x,q.y-a.y)<65);if(!near.length)return"近くのフェロモンなし";const max=Math.max(...near.map(q=>q.s));return max>.65?"強いフェロモン経路あり":max>.25?"弱いフェロモン経路あり":"フェロモンはほぼ消失"}
function updatePanel(){const [title,why]=bottleneck();bottle.innerHTML=`<b>現在のボトルネック：${title}</b><br>${why}`;if(!selected||!ants.includes(selected)){detail.innerHTML="「個体観察」を選び、気になるアリをタップ。";return}const idx=ants.indexOf(selected)+1;detail.innerHTML=`<b>#${idx}　${roleName[selected.state]||selected.state}</b><br>${taskText(selected)}<br>運搬：${selected.carry?"餌 1個":"なし"} ／ ${pherText(selected)}`}
inspectBtn.addEventListener("click",()=>{inspect=!inspect;inspectBtn.classList.toggle("on",inspect);inspectBtn.setAttribute("aria-pressed",String(inspect));overlay.style.pointerEvents=inspect?"auto":"none";inspectBtn.textContent=inspect?"🔎 個体観察中":"🔎 個体観察";if(!inspect){selected=null;trail=[];lastTrail=null}updatePanel()});
const point=e=>{const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*canvas.width,y:(e.clientY-r.top)/r.height*canvas.height}};overlay.addEventListener("pointerdown",e=>{const q=point(e);let best=null,bd=28;for(const a of ants){const d=Math.hypot(a.x-q.x,a.y-q.y);if(d<bd){bd=d;best=a}}selected=best;trail=[];lastTrail=best?{x:best.x,y:best.y}:null;updatePanel();e.preventDefault()});
const baseDrawR83=draw;draw=function(){baseDrawR83();updatePanel();if(!selected||!ants.includes(selected))return;if(!lastTrail||Math.hypot(selected.x-lastTrail.x,selected.y-lastTrail.y)>5){trail.push({x:selected.x,y:selected.y});if(trail.length>70)trail.shift();lastTrail={x:selected.x,y:selected.y}}c.save();if(trail.length>1){c.setLineDash([5,6]);c.strokeStyle="rgba(255,255,255,.48)";c.lineWidth=2;c.beginPath();trail.forEach((q,i)=>i?c.lineTo(q.x,q.y):c.moveTo(q.x,q.y));c.stroke();c.setLineDash([])}let target=null,label="";if(selected.state==="forage"){if(selected.carry){target=entrance;label="餌 → 巣"}else{target=nearestFood(selected);label="餌場へ"}}else if(selected.state==="nurse"){target=rooms[0];label="育児室へ"}else if(selected.state==="vent"){target=entrance;label="換気地点へ"}else if(selected.state==="dig"){target={x:entrance.x+Math.sin(t*.1+selected.a)*120,y:290+nest*250+Math.cos(selected.a)*70};label="掘削地点へ"}if(target){c.strokeStyle=selected.carry?"rgba(105,230,150,.9)":"rgba(255,216,90,.65)";c.lineWidth=2.5;c.setLineDash([8,7]);c.beginPath();c.moveTo(selected.x,selected.y);c.lineTo(target.x,target.y);c.stroke();c.setLineDash([]);const mx=(selected.x+target.x)/2,my=(selected.y+target.y)/2;c.fillStyle="rgba(7,16,26,.88)";c.fillRect(mx-36,my-18,72,22);c.fillStyle="#fff";c.font="bold 11px system-ui";c.textAlign="center";c.fillText(label,mx,my-3)}c.strokeStyle="#fff";c.lineWidth=3;c.beginPath();c.arc(selected.x,selected.y,13+2*Math.sin(performance.now()/180),0,Math.PI*2);c.stroke();c.strokeStyle=roleColor[selected.state]||"#ffd85a";c.lineWidth=5;c.beginPath();c.arc(selected.x,selected.y,18,0,Math.PI*2);c.stroke();c.fillStyle="rgba(7,16,26,.9)";c.fillRect(selected.x+18,selected.y-31,88,24);c.fillStyle="#fff";c.font="bold 11px system-ui";c.textAlign="left";c.fillText(`#${ants.indexOf(selected)+1} ${roleName[selected.state]||""}`,selected.x+24,selected.y-15);c.restore()};
const baseResetR83=reset;reset=function(){selected=null;trail=[];lastTrail=null;baseResetR83();updatePanel()};window.resetSimulation=reset;updatePanel();
})();
</script>'''
assert '</body>' in s
s=s.replace('</body>',extra+'\n</body>',1)
p.write_text(s,encoding='utf-8')
print('ant patched')
