from pathlib import Path
p=Path('honeybee-colony.html')
s=p.read_text()

def rep(old,new,label):
    global s
    if old not in s:
        raise SystemExit(f'{label} anchor missing')
    s=s.replace(old,new,1)

rep(".swarmModal{position:absolute;z-index:30;inset:0;display:none;align-items:center;justify-content:center;padding:18px;background:rgba(3,10,16,.78);backdrop-filter:blur(5px)}.swarmModal.show{display:flex}.swarmBox{width:min(720px,96%);border:2px solid #ffd765;border-radius:22px;background:#101d2af5;padding:18px;box-shadow:0 22px 70px #000c}",".swarmModal{position:fixed;z-index:1000;inset:0;display:none;align-items:center;justify-content:center;padding:max(14px,env(safe-area-inset-top)) 12px max(14px,env(safe-area-inset-bottom));background:rgba(3,10,16,.84);backdrop-filter:blur(5px);overflow-y:auto}.swarmModal.show{display:flex}.swarmBox{width:min(720px,96%);max-height:calc(100dvh - 28px);overflow:auto;border:2px solid #ffd765;border-radius:22px;background:#101d2af5;padding:18px;box-shadow:0 22px 70px #000c}",'swarm css')
rep("@media(max-width:700px){.swarmChoices{grid-template-columns:1fr}","@media(max-width:700px){.swarmModal{align-items:flex-start;padding:8px}.swarmBox{width:100%;max-height:none;margin:auto}.swarmChoices{grid-template-columns:1fr}",'mobile swarm css')
rep("function resourceQuality(){return clamp((honey+nectar*.12)/32,.06,1.15)*clamp((pollen+2)/16,.06,1.15)}function effectiveForageRange()","function resourceQuality(){return clamp((honey+nectar*.12)/32,.06,1.15)*clamp((pollen+2)/16,.06,1.15)}function combBuildBudget(){if(seasonIndex===3)return 0;const seasonFactor=[1,.85,.30,0][seasonIndex],warm=temp>=31?1:.2,food=clamp((honey-5)/18,0,1),work=clamp(workers/90,.25,1.2);return Math.max(0,Math.floor(Math.min(wax,(honey-5)/.6)*seasonFactor*warm*food*work))}function effectiveForageRange()",'comb budget')
rep("const buildRate=h*.022*rr.build;while(buildTargets.length&&wax>1&&Math.random()<Math.min(.95,buildRate)){const b=buildTargets.shift();if(addCell(b.q,b.r)){wax-=1;toast('⬡ 新しい巣房ができた',true)}}wax=Math.min(70,wax+h*.010*rr.build);","const buildSeason=[1,.85,.30,0][seasonIndex],buildWarm=temp>=31?1:.18,buildFood=clamp((honey-5)/18,0,1)*clamp(flowerMass/.9,.15,1.35),buildRate=h*.018*rr.build*buildSeason*buildWarm*buildFood;while(buildTargets.length&&wax>=1&&honey>=5.6&&Math.random()<Math.min(.90,buildRate)){const b=buildTargets.shift();if(addCell(b.q,b.r)){wax-=1;honey=Math.max(0,honey-.6);toast('⬡ 新しい巣房！ 蜜ろう1＋蜂蜜を使った',true)}}const waxGain=h*.0045*rr.build*buildSeason*buildWarm*clamp((honey-6)/20,0,1)*clamp(flowerMass/.9,.15,1.25);if(waxGain>0){wax=Math.min(70,wax+waxGain);honey=Math.max(0,honey-waxGain*.35)}",'build dynamics')
rep("function addBuildNear(p){const base=nearestCell(p);if(!base){toast('⬡ 巣板の端をタップしてね');return}const dirs=[[1,0],[-1,0],[0,1],[0,-1],[1,-1],[-1,1]],opts=dirs.map(([dq,dr])=>({q:base.z.q+dq,r:base.z.r+dr})).filter(a=>!cells.some(z=>z.q===a.q&&z.r===a.r)&&!buildTargets.some(z=>z.q===a.q&&z.r===a.r));if(!opts.length){toast('ここはもう巣房でいっぱい');return}opts.sort((a,b)=>Math.hypot(hexPos(a.q,a.r).x-p.x,hexPos(a.q,a.r).y-p.y)-Math.hypot(hexPos(b.q,b.r).x-p.x,hexPos(b.q,b.r).y-p.y));buildTargets.push(opts[0]);toast('⬡ 建築蜂が巣房を作りに来る',true)}","function addBuildNear(p){if(seasonIndex===3){toast('❄️ 冬は巣板を広げず、越冬を優先する',true);return}if(workers<55){toast('🐝 働き蜂が少なくて増築できない',true);return}if(temp<31){toast('🌡 巣が冷えていて蜜ろうを作りにくい',true);return}const budget=combBuildBudget();if(budget<=buildTargets.length){if(wax<1)toast('⬡ 蜜ろうが足りない。花と蜂蜜があると少しずつ作る',true);else if(honey<7)toast('🍯 蜂蜜が少ない。増築より食料確保が先',true);else toast('⬡ いま作れる分は建築予約済み',true);return}const base=nearestCell(p);if(!base){toast('⬡ 巣板の端をタップしてね');return}const dirs=[[1,0],[-1,0],[0,1],[0,-1],[1,-1],[-1,1]],opts=dirs.map(([dq,dr])=>({q:base.z.q+dq,r:base.z.r+dr})).filter(a=>!cells.some(z=>z.q===a.q&&z.r===a.r)&&!buildTargets.some(z=>z.q===a.q&&z.r===a.r));if(!opts.length){toast('ここはもう巣房でいっぱい');return}opts.sort((a,b)=>Math.hypot(hexPos(a.q,a.r).x-p.x,hexPos(a.q,a.r).y-p.y)-Math.hypot(hexPos(b.q,b.r).x-p.x,hexPos(b.q,b.r).y-p.y));buildTargets.push(opts[0]);toast('⬡ 増築予約：蜜ろう1＋蜂蜜0.6が必要',true)}",'addBuildNear')
rep("comb:'⬡ 巣板の端をタップ：建築候補を指定。建築蜂が蜜ろうで増築する。'","comb:'⬡ 巣板の端をタップ：春〜秋に増築。蜜ろう1＋蜂蜜0.6が必要。冬は建築を休む。'",'tool hint')
rep("if(workers>workerCapacity()*.86)return '群れが巣の容量に近い。⬡ 巣板を増築すると成長余地が広がる。';","if(buildTargets.length&&seasonIndex===3)return '❄ 増築予約は春まで休止。冬は蜂蜜を使って群れと巣温を守る。';if(workers>workerCapacity()*.86)return `群れが巣の容量に近い。⬡ 増築には蜜ろう1＋蜂蜜0.6が必要（今の建築余力 ${combBuildBudget()}房）。`;",'next hint')
rep("window.__beeLab={snapshot:()=>({workers:Math.round(workers),crisisHold","window.__beeLab={snapshot:()=>({workers:Math.round(workers),combBuildBudget:combBuildBudget(),wax:+wax.toFixed(2),crisisHold",'snapshot')
p.write_text(s)
